# Generated by Django 5.2.8 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
