# Generated by Django 5.2.8 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_test_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='timer_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
