# Generated by Django 5.2.8 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_test_timer_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
