# Generated by Django 5.2.8 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_permissions_notification'),
    ]

    operations = [
        migrations.AddField(model_name='enrollment', name='can_comment', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='enrollment', name='can_share_files', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='enrollment', name='can_submit_assignments', field=models.BooleanField(default=True)),
    ]
