# Generated by Django 5.2.8 on 2026-05-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_due_date_assignment_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reference_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_refs/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reference_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
